version: '3.8'

services:
  app:
    build: .
    environment:
      - PORT=${PORT}
      - HOST=${HOST}
      - PUBLIC_URL=${PUBLIC_URL}
      - TELEGRAM_URL=${TELEGRAM_URL}
    ports:
      - "${PORT}:${PORT}"